<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-ORI8JR52" ignored="0" name="Test" tests="1" failures="1" timestamp="2021-01-16T17:52:25 IST" time="67.484" errors="0">
  <testcase name="parallelRun" time="67.304" classname="courgette.api.testng.TestNGCourgette">
    <failure type="courgette.runtime.CourgetteTestFailureException" message="There were failing tests. Refer to the Courgette html report for more details.">
      <![CDATA[courgette.runtime.CourgetteTestFailureException: There were failing tests. Refer to the Courgette html report for more details.
]]>
    </failure>
  </testcase> <!-- parallelRun -->
</testsuite> <!-- Test -->
